"""empty message

Revision ID: 34ababe5a861
Revises: 50685d44b0bc
Create Date: 2022-12-07 00:22:53.320498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ababe5a861'
down_revision = '50685d44b0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.alter_column('show_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.alter_column('show_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
