"""empty message

Revision ID: 50685d44b0bc
Revises: bda700481c29
Create Date: 2022-12-03 03:21:36.677546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50685d44b0bc'
down_revision = 'bda700481c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('show_date')

    # ### end Alembic commands ###
